name: Build posts
on:
  push:
    paths:
      - "static/**"
    branches:
      - master

jobs:
  Build-posts:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "Seteando el entorno..."
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --production
      - run: npm run build:posts
      - name: GIT commit and push all posts built
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Posts
          CI_COMMIT_AUTHOR: CI
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "juliankominovic@gmail.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git checkout deploy
          git pull . master
          git push
