name: Build posts
on:
  push:
    paths:
      - "static/**"
    branches:
      - master

jobs:
  Build-posts:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "Seteando el entorno..."
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --production
      - run: npm run build:posts
      - run: rm -rf ./static/posts/*.md
      - name: Push built files
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          push-branch: "deploy"
          commit-message: "Publish release [BOT][CI]"
          force-add: "true"
          force-push: "true"
          name: JulianKominovic [CI]
          email: juliankominovic@gmail.com
          rebase: "true" # pull and rebase before commit
